spring:
  datasource:
    url: "jdbc:h2:file:~/test"
    username: "sa"
    password: ""
    driver-class-name: "org.h2.Driver"
  h2:
    console:
      enabled: true
      path: /h2

liquibase:
  change_log: "classpath:/liquibase/changelog.xml"
  enabled: true